library(rvest)
library(dplyr)
library(robotstxt)
library(stringr)

url <-"https://www.icc-cricket.com/rankings/mens/team-rankings/t20i"
path = paths_allowed(url)
web<- read_html(url)
View(web)
Team = web%>% html_nodes(".rankings-table__team")  %>% html_text()                   
View(Team)
Matches= web%>% html_nodes(".table-body:nth-child(78) .u-center-text , .table-body:nth-child(59) .u-center-text , .rankings-table__team+ .u-center-text") %>% html_text() 
View(Matches)
Points = web%>% html_nodes(".u-center-text+ .u-center-text")  %>% html_text() 
View(Points)
Ratings = web%>% html_nodes(".rating") %>% html_text() 
View(Ratings)
roll = web%>% html_nodes(".table-body__cell--position") %>% html_text() 
View(roll)
criket = data.frame(Team,Points,Ratings)
View(criket)
write.csv(criket,"cricketdetails.csv")
str(criket)
